README.md

[Its CSS postprocessor](https://github.com/cvrebert/mq4-hover-hover-shim/blob/master/src/nodejs/postprocessor.js) uses PostCSS.

Add mq4-hover-hover-shim to Tools list

---

README.md

postcss-simple-mixin and postcss-simple-extend

Added links to new plugins

---

README.md

[Postcss-host](https://www.npmjs.com/package/postcss-host) helps to make `:host` selector works properly with pseudo-classes

Add postcss-host plugin

---

API.md

I just read the first 175 lines tonight and proposed changes. I also have a few questions:
- Have you thought about documenting more specifics about parameters, e.g. expected types, whether they're optional or not, and defaults? That information is generally useful.
- I'm not certain whether my change at line 131 is fully accurate --- please have a look (presumably you'll look at all the changes.)
Nice job @ai. If you think this was useful I will look at the rest of the doc next chance I have! If there's anything you'd like me to do differently, just let me know.

Proposed edits for first 175 lines

---

lib/list.js
lib/vendor.js

Rewrite object methods to be consistent with ecmascript 6

Sixify methods

---

API.md
lib/node.js

It's antipatterns to add to prototype anything else except function

Move `defaultStyle` object from prototype to constructor

---

API.md

I made it all the way through. Some edits are above Root node because I tried to clean up the links a little bit, to make it easier to just throw in links to different parts of the documentation,  and address some of the clarifications you made.

Edits from Root node to end

---

README.md

There is no such thing as CSS4

---

README.md

Add `postcss-map` to the list of plugins

---

README.md

Refs pascalduez/postcss-quantity-queries#1

Add `postcss-quantity-queries` to plugin list

---

README.md

https://github.com/ben-eb/postcss-normalize-url

Add postcss-normalize-url.

---

README.md

Reduced description, `v4.1` branch.

Add postcss-font-family.

---

README.md

https://github.com/ben-eb/postcss-zindex

Add postcss-zindex.

---

README.md

Okay, branched from 4.1
If there are any issues please leave PR open as it's possible to fix any branching issues in the same pull request.
Cheers

Add postcss-at2x

---

README.md

https://github.com/ben-eb/postcss-discard-comments

Add postcss-discard-comments.

---

Runner Guidelines.md

Runner Guidelines - Allow using GitHub Releases

---

README.md

https://github.com/ben-eb/postcss-discard-duplicates

Add postcss-discard-duplicates.

---

README.md

https://github.com/ben-eb/postcss-merge-rules

Add postcss-merge-rules.

---

README.md

Now with a single lien description

Add postcss-pseudoelements to README.md

---

README.md

* https://github.com/ben-eb/postcss-discard-empty
* https://github.com/ben-eb/postcss-minify-selectors

Add discard-empty, minify-selectors.

---

README.md

Port of [rework-plugin-url](https://github.com/reworkcss/rework-plugin-url) to PostCSS
https://github.com/simonsmith/postcss-map-url
Noticed you've merged the `4.1` branch so have chosen `master` for this PR

Add postcss-map-url

---

README.md

https://github.com/ben-eb/postcss-colormin

Add postcss-colormin.

---

README.md

https://github.com/ben-eb/postcss-discard-font-face

Add postcss-discard-font-face.

---

README.md

Add line about postcss-messages plugin

---

README.md

https://github.com/antyakushev/postcss-default-unit

Add postcss-default-unit to plugin list

---

README.md

https://github.com/ben-eb/postcss-minify-font-weight

Add postcss-minify-font-weight.

---

package.json

Ref. https://github.com/yeoman/generator-gulp-webapp/pull/298#issuecomment-89869297

Move promise polyfill to dependencies

---

README.md

https://github.com/ben-eb/postcss-convert-values

Add postcss-convert-values.

---

README.md

https://github.com/ben-eb/postcss-reduce-idents

Add postcss-reduce-idents.

---

Runner Guidelines.md

I've rewritten the guidelines to use a clear, more consistent tone. :smile:

Update runner guidelines.

---

README.md

https://github.com/ben-eb/cssnano

Add cssnano.

---

README.md

https://github.com/jo-asakura/postcss-neat

Add postcss-neat plugin

---

README.md

Addresses btholt/postcss-colorblind#1
Thanks!

Add postcss-colorblind to Others

---

README.md

https://github.com/andyjansson/postcss-conditionals

Add postcss-conditionals plugin

---

README.md

Canadian Style Sheets, I can haz?

---

README.md

https://github.com/ben-eb/postcss-merge-idents

Add postcss-merge-idents.

---

README.md

https://github.com/morishitter/postcss-style-guide

Add postcss-style-guide to README

---

README.md

Hoping I got the markdown alignment correct! :)

Add postcss-property-lookup

---

README.md

Add postcss-class-prefix plugin to the readme

add postcss-class-prefix

---

README.md

https://github.com/andyjansson/postcss-grid

Add postcss-grid to README.md

---

README.md

These plugins add the functionality demonstrated on http://hallvord.com/temp/moz/cssfixme.htm to PostCSS

Add links to my two new plugins

---

README.md

http://github.com/seaneking/postcss-position

Add postcss-position plugin to README

---

README.md

http://dev.w3.org/csswg/selectors-4/#the-any-link-pseudo

Add postcss-pseudo-class-any-link

---

README.md

Add PostStylus to README

---

README.md

Every time I see PostCSS readme, I wanna cry because of "strange" native gitter badge. let’s use custom badge!
Text, color and style are configurable. Probably, we can use modern _flat-square_ style. Take a look at [shields.io page](http://shields.io/)

fix native gitter badge

---

README.md

https://github.com/seaneking/postcss-hexrgba

Add postcss-hexrgba to README

---

README.md

https://github.com/seaneking/postcss-clearfix
Similar functionality already covered in https://github.com/cssdream/cssgrace but I wanted this as a standalone plugin.

Add postcss-clearfix to README

---

README.md

add postcss-color-mix to plugins’ list

---

lib/tokenize.js

Some style correction, and handwrite char codes

Optimize and idiomantify tokenizer

---

.yaspellerrc
README.md

add postcss-color-pantone to plugins list

---

README.md

https://github.com/seaneking/postcss-fontpath

add postcss-fontpath to README

---

README.md

https://github.com/seaneking/postcss-alias

add postcss-alias to README

---

lib/lazy-result.js
test/postcss.js

Do we need more tests than this one? It is passing all current tests.

Support runtime plugin injection.

---

README.md
docs/api.md

Cleaned up some of the wording : )

Grammatical fixes and README proofreading

---

README.md

https://github.com/simplaio/rucksack
Bourbon/Nib/etc. style helper framework with shortcuts and extra features to speed up CSS development.
Includes optional extras like autoprefixing and normalization that can be toggled on/off with options, so plays nice with other packs like `cssnext`.

Add Rucksack to README

---

README.md

https://github.com/omgovich/postcss-pseudo-elements-content

Add postcss-pseudo-elements-content to README

---

docs/api.md
lib/container.js

For your consideration; update `eachRule` to support a conditional filter, as `eachDecl` does.

Support selector filter on eachRule

---

package.json

`postproccessor` is wrong, it's "postprocessor".
I also updated the list a little bit ;)

Fix and update npm keywords

---

README.md

@ai as discussed. Added link to postcss-mq-keyframes in the 'others' section

added link to postcss-mq-keyframes in the others section

---

README.md

added postcss-scopify to plugins listing in README.md

added link to postcss-scopify

---

README.md

https://github.com/seaneking/postcss-responsive-type

Add postcss-responsive-type to README

---

README.md

[`postcss-circle`] inserts a circle with color.
[`postcss-circle`]:                 https://github.com/jedmao/postcss-circle

Add postcss-circle to README

---

README.md

[`postcss-center`] centers elements.
[`postcss-center`]:                 https://github.com/jedmao/postcss-center

Add postcss-center to README

---

appveyor.yml

@ai you still need to sign up with your GitHub account on [AppVeyor](http://www.appveyor.com/), add a new project and then switch on postcss for it to run builds. Not unlike Travis-CI, really.

Run tests w/ AppVeyor

---

README.md

It adds a little more logic for css3 filters.

Added a tyny plugin

---

README.md

My first PostCSS plugin. Apologies for any mistakes. Just thought it would be fun to support Imperial units in CSS.

PostCSS plugin for Imperial and US customary units

---

README.md

[`postcss-triangle`] creates a triangle.
[`postcss-triangle`]:               https://github.com/jedmao/postcss-triangle

Add postcss-triangle to README

---

README.md

Add CSSfmt to README

---

README.md

`postcss-increase-specificity`: https://github.com/MadLittleMods/postcss-increase-specificity
Increase the specificity of your selectors.

Add postcss-increase-specificity to plugin list

---

README.md

`postcss-russian-units`: https://github.com/Semigradsky/postcss-russian-units

Add `postcss-russian-units` to plugin list

---

README.md

https://github.com/seaneking/postcss-input-style

add postcss-input-style to README

---

README.md

Rucksack now has a fancy website - http://simplaio.github.io/rucksack

update rucksack link in README

---

README.md

Would you like to have some [sauerkraut](https://github.com/timche/postcss-german-stylesheets)?

Add German Style Sheets to README.md

---

README.md

Feel free to decide whether it's worth adding it to the list of not, as the "spec" and plugin are incomplete.

Add postcss-apply to plugin list

---

README.md

add Fly plugin to README

---

lib/map-generator.es6
test/map.es6
test/processor.es6
test/root.es6

Close #535 
> related: https://github.com/MohammadYounes/rtlcss/issues/40#issuecomment-136398458

Use appropriate End-of-line marker for current OS.

---

lib/postcss.es6

I think this a little cleaner and nicer =)

Add more ES6

---

README.md

Added Swedish Stylesheets

---

lib/parser.es6

This fixes postcss/postcss-scss#5
Not sure if this is direction you want to go, but it collects as many words it can find into the property

allow multiple words in property

---

README.md

Add `postcss-russian-stylesheets` to plugin list

---

README.md

Refer to discussion at https://github.com/postcss/postcss-simple-vars/issues/27

Add postcss-nested-vars to readme

---

README.md

* [postcss-instagram](https://github.com/azat-io/postcss-instagram)
* [postcss-responsive-images](https://github.com/azat-io/postcss-responsive-images)
* [postcss-tatar-stylesheets](https://github.com/azat-io/postcss-tatar-stylesheets)

Add new plugins to readme

---

README.md

Many moons ago, we wanted this to be a plugin pack. Well, I finally got around to it. https://github.com/jonathantneal/postcss-short/issues/3

Update short plugin pack

---

README.md

[`postcss-reverse-media`](https://github.com/MadLittleMods/postcss-reverse-media)
> Reverse/Invert media query parameters
Input:
```css
@media reverse (max-width: 150px) { /*...*/ }
@media reverse (min-width: 150px) { /*...*/ }
```
Output:
```
@media (min-width: 150.001px) { /*...*/ }
@media (max-width: 149.999px) { /*...*/ }
```

Add postcss-reverse-media to readme

---

.yaspellerrc

Add 'gitter' to .yaspellerrc

---

lib/previous-map.es6
test/previous-map.es6

Detect source-maps created by mozilla/source-map fix #583

---

README.md

plugin converts rgb/rgba values to hex analogues.
currently functionality is limited, but it's the matter of time.
plans for nearest future - add bg color mix support

added rgba-hex plugin

---

README.md

Add plugin link sorted alphabetically 
Add link sorted by length

Add postcss-shades-of-gray link

---

README.md

Adds postcss-cachebuster plugin

---

README.md

https://github.com/HoBi/postcss-czech-stylesheets

Add `postcss-czech-stylesheets` to plugin list.

---

README.new.md

Ref: https://github.com/postcss/postcss/issues/656

Improve grammar, spelling corrections.

---

README.md

fix sample code on README.md

---

docs/plugins.md

by @ai request
https://github.com/glebmachine/postcss-easysprites/issues/3

postcss-easysprites added to plugins.md

---

.yaspellerrc
docs/writing-a-plugin.md

In response to https://github.com/postcss/postcss/issues/178#issuecomment-162715224.

Add more tools to writing-a-plugin.md

---

docs/plugins.md

Add postcss-selector-prefixer plugin - adds a prefix to css selectors.

Add postcss-selector-prefixer plugin

---

docs/plugins.md

add postcss-selector-prefixer plugin to others section

---

docs/plugins.md

Add current-selector reference into plugins documentation

Add postcss-current-selector plugin into documentation

---

docs/api.md

I found a couple of broken links, so I fixed them.

Fix links in API.md

---

docs/plugins.md

Testing is currently a single end-to-end test. Let me know if it needs more test coverage and/or smaller unit tests.

Add postcss-scrib to plugins.md (under Shortcuts)

---

docs/plugins.md

add my plugin postcss-font-normalize.

add my plugin postcss-font-normalize

---

docs/plugins.md

This is good to go once https://github.com/lukelarsen/postcss-hidden/pull/7 is merged. :smile:
/cc @lukelarsen
ref: https://github.com/postcss/postcss/pull/642

Add postcss-hidden to plugins list.

---

docs/plugins.md

Add [postcss-filter-stream](https://github.com/tsm91/postcss-filter-stream) plugin to plugins list.

Add postcss-filter-stream plugin to plugins list.

---

docs/api.md

When using append/prepend to add an atrule, name: should not include @.

Update api.md with correct method to add an atrule.

---

docs/api.md

Yes! I'm a PostCSS contributor now!!!

RED ALERT! TYPO!

---

README.md
docs/guidelines/runner.md

update references to postcss-cli

---

lib/root.es6

Hi,
Just spotted this `if` inside the loop, which could be moved outside and increase slightly the performance. Hope it helps.
Cheers

Move condition up the loop

---

docs/plugins.md

[postcss-aspect-ratio](https://github.com/arccoza/postcss-aspect-ratio)
[postcss-if-media](https://github.com/arccoza/postcss-if-media)
[postcss-layout](https://github.com/arccoza/postcss-layout)

Add postcss-aspect-ratio, postcss-if-media & postcss-layout to plugins.md

---

README.md

I noticed #656 and thought I'd have a look through the Readme and see if I could come up with any wording improvements. Here are my suggestions. 
Really like the new Readme, by the way.

Suggested tweaks to Readme

---

CHANGELOG.md

Add unrelesed section and semver info to changelog

---

docs/api.md

Addresses https://github.com/postcss/postcss/issues/737

Fix origin source object in API docs

---

gulpfile.babel.js
package.json

In response to https://github.com/postcss/postcss/pull/746#issuecomment-188988230

Move typings to package.json

---

docs/plugins.md

Add postcss-oldschool-grid plugin under Grids section.

Add postcss-oldschool-grid plugin

---

d.ts/at-rule.d.ts
d.ts/container.d.ts
d.ts/css-syntax-error.d.ts
d.ts/lazy-result.d.ts
d.ts/node.d.ts
d.ts/parser.d.ts
d.ts/postcss.d.ts
d.ts/previous-map.d.ts
d.ts/processor.d.ts

TypeScript definitions have been updated to align with latest master.

Update TypeScript definitions

---

README.md

Could you feature stylefmt on README? :)
Thanks.

Add stylefmt to plugins list on README

---

docs/plugins.md

* Added `postcss-magic-animations` to the list of plugin.

Added  postcss-magic-animations in Shortcutst

---

README.md

under a new IDE section.
Signed-off-by: Daniel Bayley <daniel.bayley@me.com>

Add source-preview-postcss to README

---

docs/plugins.md

- postcss-button
- postcss-typescale
- postcss-grid-fluid
- postcss-grid-system

Add 4 plugins to the list

---

docs/plugins.md

postcss-placehold makes it easy to drop in placeholder images.

Add postcss-placehold plugin

---

docs/plugins.md

Added camelcasing plugin to plugin list.
https://github.com/GMchris/postcss-camelcaser

Add Camelcaser to plugins.

---

d.ts/at-rule.d.ts
d.ts/comment.d.ts
d.ts/container.d.ts
d.ts/css-syntax-error.d.ts
d.ts/declaration.d.ts
d.ts/input.d.ts
d.ts/lazy-result.d.ts
d.ts/node.d.ts
d.ts/parse.d.ts
d.ts/postcss.d.ts
d.ts/processor.d.ts
d.ts/result.d.ts
d.ts/root.d.ts
d.ts/rule.d.ts
d.ts/stringify.d.ts
d.ts/warning.d.ts

Fixes #787 
Sorry it took so long to figure out, @kourge.

Fix TypeScript module resolution

---

docs/plugins.md

Added postcss-ie8 link to the plugins in section "Other" 

---

docs/writing-a-plugin.md

Fixed issue with PostCSS API link in the docs

---

lib/node.es6

Fixes spelling error in cloneBefore/After (docs)

---

docs/plugins.md

I've added it into "Packs", but perhaps we could also add into "Shorcuts".

Add postcss-utilities

---

docs/plugins.md

[UnCSS](https://github.com/giakki/uncss) is now available as a postcss plugin! https://github.com/RyanZim/postcss-uncss

Add postcss-uncss

---

docs/plugins.md

Add [postcss-randomcolor](https://github.com/alanev/postcss-randomcolor)

Add postcss-randomcolor

---

docs/plugins.md

Specification: https://www.w3.org/TR/selectors4/#attribute-case
Plugin documentation: https://github.com/Semigradsky/postcss-attribute-case-insensitive

Add `postcss-attribute-case-insensitive` plugin

---

docs/plugins.md

Updated ordering as mentioned previously.

postcss-forced-variable in plugins.md

---

lib/css-syntax-error.es6
lib/terminal-highlight.es6
test/css-syntax-error.js

I basically fixed the same bugs that I’ve fixed in babel-code-frame before ;)
See each commit for details.

Various terminal highlighter fixes

---

docs/plugins.md

Not sure if i got the ordering correct. It seems all over the place 😅

Added postcss-italian-stylesheets in plugins.md

---

lib/container.es6

`{string} opts.prop` --> `{string|string[]} opts.props`

Fix container.replaceValues JSDoc

---

README.md

It was moved to Brunch organization

Update url of postcss-brunch

---

docs/plugins.md

This is my first plugin for PostCSS - feedback welcome!

Add postcss-filter-tint plugin to list

---

lib/tokenize.es6
test/css-syntax-error.js
test/parse.js
test/tokenize.js

Ref: https://github.com/ben-eb/gulp-cssnano/issues/70

Fix: Unclosed quote => Unclosed string

---

docs/plugins.md

Add postcss-ref to plugins.md

---

docs/plugins.md

Add postcss-lazyimagecss to plugins.md 

---

docs/plugins.md

Added plugins:
* [`postcss-closest`]
* [`postcss-text-remove-gap`]
[`postcss-text-remove-gap`]: https://github.com/m18ru/postcss-text-remove-gap
[`postcss-closest`]: https://github.com/m18ru/postcss-closest

Added two plugins

---

README.md

Added `postcss-rtl` plugin that generates RTL-styles and combines both-directional styles in one file.

Added postcss-rtl plugin to plugins list

---

docs/plugins.md

Added a plugin [postcss-border-9-patch](https://github.com/teaualune/postcss-border-9-patch) to help 9-patch styles generation.

add postcss-border-9-patch

---

docs/plugins.md

Add postcss-stylestats to plugins.md

---

docs/plugins.md

as suggested 
https://github.com/sylvainpolletvillard/postcss-grid-kiss/issues/1

Add postcss-grid-kiss to plugins.md

---

docs/plugins.md

add 2 plusins `postcss-pie` & `postcss-unprefix`

add 2 plusins `postcss-pie` & `postcss-unprefix`

---

docs/plugins.md

Recently added to cssnext 2.9.0
https://github.com/MoOx/postcss-cssnext/blob/master/CHANGELOG.md#290---2016-11-28

Added: postcss-color-hsl & postcss-color-rgb

---

lib/processor.es6

Reference: https://github.com/postcss/postcss/commit/da790db2438726e9c341233928adfa4c708ef6c4

Update wording for using a PostCSS syntax as a plugin.

---

docs/plugins.md

Just adding my PostCSS plugin reference to the Plugin section.

Add postcss-nope to Plugin section

---

docs/plugins.md

add postcss-pseudo-element-cases and postcss-pseudo-element-colons plugins to plugin reference.

add postcss-pseudo-element-cases postcss-pseudo-element-colons

---

docs/plugins.md

add postcss-define-function to plugins list.

add postcss-define-function plugin to plugins.md

---

lib/postcss.d.ts

Reverts #950 
Fixes #954 
Sorry for the wait, everybody. I had to do some testing to reproduce the problem on my end first so that I could verify this was the issue. Just need to revert this change.

Revert "Fix TypeScript module export"

---

lib/container.es6

Change `container` methods description in docs

---

docs/plugins.md

As suggested by @ai in https://github.com/tivac/fixie/issues/1
:+1:

advertise postcss-fixie

---

docs/plugins.md

Add postcss-lazysprite to plugins.md

---

README.md

Hi there!
I've made a small css func polyfill, hope somebody will find it very useful. 
So I propose add it to plugins list.

add postcss-image-set-polyfill to plugins list

---

README.md

This PR shows a basic webpack/PostCSS config

Webpack 2 config example

---

lib/map-generator.es6

Buffer we have only in Node.JS.

Add Browsers support in map-generator.es6

---

docs/plugins.md

Add postcss-state-selector to plugins

Add new plugin

---

lib/tokenize.es6
test/tokenize.test.js

Hello, sir.
This simple patch closes #1042 .

Fixed issue with unicode escapes.

---

lib/parser.es6

Hi, it closes #1046 
Currently breaks build, need to update `postcss-parser-tests`
> Not happy with solution, maybe i will come with something better unified later.

Fixed problem with matching at-rule end in rule context

---

lib/lazy-result.es6
test/processor.test.js

Improve info message for unknown error

---

docs/plugins.md

`size: width min-width max-width / height min-height max-height / padding / margin;`

Add postcss-size-advanced

---

README.cn.md
README.md

Fixed both in Chinese and English version.

README: image-set W3 Draft URL fixed

---

.yaspellerrc
README.cn.md
README.md

Hello
`Fly` build system currently abandoned in favour of [`Taskr`](https://github.com/lukeed/taskr).
Please, consider adding proper `postcss` plugin to build systems list.

 Removed abandoned Fly plugin and added Taskr

---

lib/postcss.d.ts

`source-map` provides ts typings so would be nice to get benefits from it.

Improved typescript declarations for source maps

---

docs/plugins.md

https://github.com/zachleat/postcss-foft-classes

Adds postcss-foft-classes.

---

docs/plugins.md

This plugin is no longer maintenanced.
https://github.com/kubosho/postcss-stylestats

Remove postcss-stylestats

---

docs/plugins.md

Add postcss-nested-ancestors

---

README-cn.md
README.md

- `postcss-syntax` PostCSS auto syntax switch tool
- `postcss-styled` allows you to write styles in styled-components

Add new syntax

---

docs/plugins.md

 Added postcss-font-display to plugins list. 

---

.yaspellerrc
lib/lazy-result.es6
test/lazy-result.test.js

I try to resolve issue #1146.
Please, review my PR and give me feedback.

Added finally method to LazyResult

---

README.md

Improve README introduction

---

README.md
docs/plugins.md

This plugin based on a really simple idea: download remote files in `@font-face` and update CSS, so internal project stays internal. But people could do more with local font files!
https://github.com/AaronJan/postcss-font-grabber

Submit a plugin: `postcss-font-grabber`

---

docs/plugins.md

Checkout my awesome plugin! 👍🎉👻🦕
https://github.com/crftd/postcss-glitch

Submit postcss-glitch plugin

---

lib/tokenize.es6

Merged cases that do the same job
Returning a single token that matches with case
Can be solved easily by converting the ASCII back to a character using String.fromCharCode

Merge cases

---

docs/plugins.md

added link to the according blogpost

cssnext is deprecated

---

docs/plugins.md

Add a new plugin to docs/plugins.md.

Add postcss-plugin-namespace to docs/plugins.md

---

docs/plugins.md

add px-to-viewport plugin to plugins

---

docs/plugins.md

Add missing URL for postcss-font-grabber

Fix broken link

---

docs/plugins.md

Update postcss-bem to postcss-bem-fix to support the latest version of postcss.

Fix broken link (#1249)

---

package.json

I changed the link on the theme

Change repo for theme of docs

---

lib/postcss.d.ts

https://api.postcss.org/Result.html#warnings
https://api.postcss.org/LazyResult.html#warnings

fix(types): return `Warning[]` from `warnings()`

---

lib/postcss.d.ts

Add the stringifier argument to NodeBase.prototype.toString()'s type

---

lib/postcss.d.ts
lib/previous-map.es6
test/previous-map.test.js

Inspired by #1294, another attempt since that one is closed.

Fix: Reads only the last sourceMappingURL in the file

---

docs/plugins.md

Adds [postcss-color-image](/valtlai/postcss-color-image) to the *Future CSS Syntax* section.

Add plugin to list

---

docs/plugins.md

word correction - **posctss-preset-env** to **postcss-preset-env**

Update plugins.md - Spelling Correction

---

CONTRIBUTING.md
README.md

1. Rephrasing a couple of things in `CONTRIBUTING` for better readability.
2. Fixing a sentence meaning & punctuation in `README` usage.

docs: Update wording, typos, punctuation

---

docs/plugins.md

[postcss-deadcss](https://github.com/DenyVeyten/postcss-deadcss)

Added postcss-deadcss in the list of plugins

---

docs/writing-a-plugin.md

PR for https://github.com/postcss/postcss/issues/1435 issue

Add note to docs about Symbol() usage

---

docs/plugins.md

Please retweet [this](https://twitter.com/Andrej_Gajdos/status/1330575931690389506) if it's possible.

add postcss-grid-reset and postcss-flexbox-reset

---

lib/postcss.d.ts

Expose LazyResult type

---

lib/fromJSON.js
lib/node.js
lib/postcss.d.ts
test/fromJSON.test.ts
test/node.test.ts

Closes https://github.com/postcss/postcss/issues/1502
I did not know that `JSON.stringify` actually calls `toJSON` on objects...

Fix JSON.stringify of an array of nodes

---

docs/plugins.md

https://github.com/iagafonov/postcss-add-root-selector

Add postcss-add-root-selector to plugins list

---

lib/list.d.ts

fix https://github.com/postcss/postcss/issues/1576

fix List declartation

---

CHANGELOG.md

7.0.33 to 7.0.36 were duplicated.

Fix duplicate changelog

---

docs/README-cn.md

zh-cn translation not up to date.

docs: add instructions for CSS-in-JS & Parcel

---

package.json

Following from https://github.com/postcss/autoprefixer/pull/1448

Update `funding` key in package.json

---

test/postcss.test.ts

Fix typo in postcss.test.ts

---

docs/plugins.md

This PR resolves  #1723 issue.

add postcss-easy-import to the plugin list

---

docs/writing-a-plugin.md

Moved title to allow documentation pages to generate properly.

Move title

---

docs/architecture.md

Change title

---

lib/node.js

see : https://github.com/postcss/postcss/issues/1847

reduce calls to `Node.prototype.toString()`

---

docs/plugins.md

Add the [`postcss-urlrebase`](https://github.com/strarsis/postcss-urlrebase) plugin to the plugins page.

Add `postcss-urlrebase` plugin to plugins page

---

docs/plugins.md

`postcss-plugin-ignore-file`
- Github repo : https://github.com/RiadhAdrani/postcss-plugin-ignore-file
- NPM package : https://www.npmjs.com/package/postcss-plugin-ignore-file

add `postcss-plugin-ignore-file` to plugins.md

---

lib/parser.js

fixes : https://github.com/postcss/postcss/issues/1870
depends on : https://github.com/postcss/postcss-parser-tests/pull/25

add `source.end` to `Root` nodes

---

README.md
docs/README-cn.md
docs/guidelines/plugin.md
docs/plugins.md

Updated the addresses in the document that were returning errors, inaccessible, or had changed to different locations

Fix unreachable urls

---

lib/container.d.ts
lib/lazy-result.js
lib/node.d.ts
lib/node.js
lib/postcss.d.ts

These are useful when writing a package like the Sass parser that inherits from PostCSS types.

Add protected methods

---

package.json
pnpm-lock.yaml

Infinite loop in nanoid <3.3.8 
See https://github.com/advisories/GHSA-mwcw-c2x4-8c55

Pins nanoid to ^3.3.8

---

lib/node.js

See: https://github.com/stylelint/stylelint/issues/8312#issuecomment-2589474116

Improve backwards compatibility for `Input#document`

---

docs/plugins.md

[`postcss-auto-var-fallback`] adds var fallbacks by provided files of variables

add postcss-auto-var-fallback fallback plugin to plugins.md

---

lib/node.js
test/node.test.ts

Fix `opts` argument of `Node#rangeBy()` and `Node#positionBy()` cannot be omitted

---

lib/node.d.ts
lib/node.js
test/node.test.ts

Fix missing offset in `Node#positionInside`, `Node#positionBy` and `Node#rangeBy`

---

lib/node.js

when using postcss using parcel 
an error was occuring due to  no check mentioned for value at line 401 , which caused error while reading value when it was undefined hence i added a check if its value is undefined continue and dont move forward

fixed error at line 401
