postcss/postcss

README.md

[postcss-single-charset][1] is for popping first `@charset` rule to the top of CSS file. This plugin is for fixing wrong `@charset` rule position after concatenate CSS files.
[1]: https://github.com/hail2u/postcss-single-charset

Add postcss-single-charset plugin

---

API.md

Just saying it returns a Result captures it, right?

Simplify API's root.toResult() description

---

.gitignore
gulpfile.js
package.json

This adds a standalone build much like what is present in [postcss/autoprefixer-core][apc]. This will allow us to more easily integrate postcss support into [OpenNTF/JavascriptAggregator][jaggr].
My employer wishes to express that this is intended for release under the MIT license. :shipit: 
[apc]: https://github.com/postcss/autoprefixer-core "autoprefixer-core"
[jaggr]: https://github.com/OpenNTF/JavascriptAggregator "JavascriptAggregator"

Add standalone build.

---

gulpfile.js

Update the build gulp task to reflect 6to5's new name so it doesn't get pulled as dep in npm installs.

6to5 -> babel in build:package

---

lib/postcss.js
package.json
test/postcss.js

In this PR I suggest to use [`semver.satisfies`](https://github.com/npm/node-semver) to match postcss version.

Use semver to match postcss version

---

API.md

As far as I know, `vendor` module should import before using it.

Clarify how to import `vendor` module

---

lib/map-generator.js

Hello postcss developers,
I came across an issue using Autoprefixer on CSS files with source maps generated by Less.js which caused an unhandled `TypeError: Cannot call method 'map' of null` to be thrown.  The issue can be reproduced using the following code (with autoprefixer-core 5.1.7 and less 2.4.0):
```javascript
less.render(".flexy { display: flex; }", {sourceMap: {}})
.then(function(lessOutput) {
var autoprefixerOutput = autoprefixer().process(
lessOutput.css,
{
map: {
prev: lessOutput.map,
sourcesContent: false
}
}
);
try {
console.log(autoprefixerOutput.css);
} catch (err) {
console.error(err);
console.error(err.stack);
}
});
```
The issue appears to be that when the `sourcesContent` option is `false`, the attempt to remove any source content from the previous source map does not …

Unhandled exception if previous source map is missing sourcesContent

---

lib/parser.js
test/cases/important.css
test/cases/important.json

So now we can parse a declaration such as this correctly:
```css
h1 {
color: black      !    /* test comment */   important;
}
```

Parse spaces & comments inside important. Fixes #253.

---

lib/container.js
test/container.js

Hello!
I think it might be helpful to provide the developer with a nice error message when a declaration is attempted to be added to a container like so:
```
rule.append({
prop: 'transform',
vlaue: 'translate(-50%, -50%)'
});
```
In this case, the developer has incorrectly specified the value of the rule under something other than 'value' key. Currently the error message is:
```Cannot call method 'indexOf' of undefined```
with no discernible source or traceback (at least through Grunt). 
This patch adds some nicer diagnostics, including what I hope to be a more helpful error message:
```Could not construct declaration; 'value' field unspecified.```, 
as well as an additional check for the `prop` key. 
Corresponding tests for the test suite are included.

Helpful error message for when adding to containers

---

package.json

I guess this needs to be a production dependency, at least my node 0.10 build fails otherwise.

Move es6-promise to prod dependencies

---

API.md

Fix typo in `API.md`

---

README.md

[`postcss-css-variables`](https://github.com/MadLittleMods/postcss-css-variables) transforms [CSS Custom Property syntax(CSS variables)](http://dev.w3.org/csswg/css-variables/) into static representation that can be used today.
[Try it out on the code playground](http://localhost/random/postcss-test1/node_modules/postcss-css-variables/playground/) or checkout the [usage section in the readme](https://github.com/MadLittleMods/postcss-css-variables#usage).
It works out the proper variable scope for descendant or nested rules/selectors to assign the associated value.
It also works with `@rules` such as media queries and updates any property that references the variable when the media query is active.

Add postcss-css-variables plugin

---

README.md

This PR adds a link to the Australian Stylesheets plugin, providing a local language option for Australian developers.
```css
.foo {
colour: true-blue !bloody-oath;
border: yeah-nah;
}
```
```css
.foo {
color: #0581C1 !important;
border: none;
}
```

Add Australian Style Sheets to readme

---

README.md

[`postcss-css-variables`](https://github.com/MadLittleMods/postcss-css-variables) now [supports pseudo selectors](https://github.com/MadLittleMods/postcss-css-variables#pseudo-class-and-elements).

Update postcss-css-variables plugin description

---

README.md

It's a pseudo selector per w3c spec :)

Fix custom-selector example

---

README.md

Since this plugin does not provide a future proof code (see https://github.com/MadLittleMods/postcss-css-variables/issues/4) and documentation is still misleading and unclear about the differences, I think it does not belong into this section.

Move `postcss-css-variables` out of `Future CSS Syntax` section

---

README.md

Planned for integration in cssnano 3.x, which will use the async API. Right now it can be used standalone. :smile:

Add postcss-svgo to the readme.

---

README.md

postcss-log-warnings reports that it is deprecated and users should get postcss-reporter instead.

Swap postcss-log-warnings for postcss-reporter

---

docs/api.md

Now, when semicolon is ommited, `atrule.semicolon` and `rule.semicolon` returns `false`.

Fix API docs

---

README.md

Just a simple postcss plugin to create shorthand properties for Crips that are too lazy to write.

Added postcss-crip

---

README.md

Although It's pending approval from @MoOx for cssnext, all it's functionality is either compliant with the [spec](https://tabatkins.github.io/specs/css-extend-rule) or is a documented difference that throws warnings. I've already written up a quick ['TLDR' of deviances in a cssnext issue](https://github.com/cssnext/cssnext/issues/189).
If you'd still rather have this filed under a 'language extension', I'm happy to redo the PR.
Also included:
Slight language change on postcss-simple-extend to further emphasize the difference between plugins.
Fixed the placement of postcss-scopify's url to match the order.
This closes issue #321.

Add postcss-extend to readme (as future syntax)

---

README.md

[`postcss-all-link-colors`] insert colors for link-related pseudo-classes.
[`postcss-all-link-colors`]:        https://github.com/jedmao/postcss-all-link-colors

Add postcss-all-link-colors to README

---

README.md

Figure this will be useful here now that it's `1.0`, and closes johnotander/immutable-css/issues/13 created by @ai. Currently, this tool doesn't exactly function as a PostCSS plugin. However, it does use PostCSS, and incorporating the PostCSS plugin API is on the [roadmap](https://github.com/johnotander/immutable-css/issues/20).

Add immutable-css tool to analysis section

---

README.md

To make it easier to find the plugin users are looking for, mention [postcss.parts](http://postcss.parts) in the README.

Mention postcss.parts in README

---

.yaspellerrc
d.ts/at-rule.d.ts
d.ts/comment.d.ts
d.ts/container.d.ts
d.ts/css-syntax-error.d.ts
d.ts/declaration.d.ts
d.ts/input.d.ts
d.ts/lazy-result.d.ts
d.ts/list.d.ts
d.ts/map-generator.d.ts
d.ts/node.d.ts
d.ts/parse.d.ts
d.ts/parser.d.ts
d.ts/postcss.d.ts
d.ts/previous-map.d.ts
d.ts/processor.d.ts
d.ts/result.d.ts
d.ts/root.d.ts
d.ts/rule.d.ts
d.ts/stringifier.d.ts
d.ts/stringify.d.ts
d.ts/tokenize.d.ts
d.ts/vendor.d.ts
d.ts/warn-once.d.ts
d.ts/warning.d.ts
docs/api.md
docs/syntax.md
postcss.d.ts

Based on https://github.com/postcss/postcss/pull/489
This PR introduces [TypeScript](http://www.typescriptlang.org/) definitions, of particular interest to PostCSS plugin developers using [Visual Studio](https://www.visualstudio.com/), now [free for open source developers](https://www.visualstudio.com/products/visual-studio-community-vs) and [available across platforms](https://www.visualstudio.com/products/code-vs). Using these definitions, you gain in-editor insight into the PostCSS API via [Intellisense](https://en.wikipedia.org/wiki/Intelligent_code_completion#IntelliSense) w/o the need to pull up documentation in a separate browser window.
The definitions for this project expose only public API members. Everything else is hidden from you, so you can relax, knowing you are following …

Introduce TypeScript definitions

---

d.ts/container.d.ts
d.ts/postcss.d.ts
docs/api.md
lib/container.es6
lib/map-generator.es6
lib/stringifier.es6
test/container.es6
test/map.es6
test/postcss.es6
test/processor.es6

Fixes #487 
No rush, just trying to get a head start on this one.
Deprecates `each` methods in favor of similarly-named `walk` methods.

Rename recursive `each` methods to `walk` methods

---

postcss.d.ts

This fixes an error when trying to `import postcss from 'postcss';`:
```
19:06 $tsc
lib/plugin.ts(2,8): error TS1192: Module ''postcss'' has no default export.
```
The previous export was the old way, this is the new (ES6) way.

Fix postcss.d.ts export

---

.gitignore
.npmignore
gulpfile.babel.js
package.json

Fixes #501 
Note the `--statements 89.12 --branches 81.85 --functions 87.29 --lines 91.71` are all locked at the current coverage values. We can increase these numbers as more tests are written.

Introduce code coverage with Isparta/Istanbul

---

README.md

Attempt no. 2 at getting [`postcss-rgb-plz`](https://github.com/himynameisdave/postcss-rgb-plz) added to the list of plugins.
`postcss-rgb-plz` is a super simple plugin that converts basic 3/6 digit hex values to their rgb counterpart. We use it at my work to maintain consistency between alpha'd and non-alpha'd colours in our outputted CSS. So for instance we don't want our stylesheets to be jumping around between `#fff` and `rgba( 255, 255, 255, 0.5 )`, we'd rather just use `rgb( 255, 255, 255 )` instead of the hex value altogether. It's really just a consistency thing, there's not some hidden performance improvement.
Although some developers have pointed out that this is silly, the plugin does meet all the plugin requirements and I would like to add it to the "official" list. Mostly …

Add postcss-rgb-plz to list of plugins

---

docs/api.md

Changed 'you CSS' to 'your CSS' in a documentation example.

Fix small spelling error

---

README.md

Adds [`postcss-round-subpixels`](https://github.com/himynameisdave/postcss-round-subpixels) to the list of plugins.
It rounds out decimal values in pixels, because [browsers are inconsistent](http://cruft.io/posts/percentage-calculations-in-ie/) in their dealing with them.

adds postcss-round-subpixels to readme

---

d.ts/at-rule.d.ts
d.ts/comment.d.ts
d.ts/container.d.ts
d.ts/css-syntax-error.d.ts
d.ts/input.d.ts
d.ts/lazy-result.d.ts
d.ts/node.d.ts
d.ts/postcss.d.ts
d.ts/processor.d.ts
d.ts/result.d.ts
d.ts/root.d.ts
d.ts/rule.d.ts
d.ts/stringify.d.ts
d.ts/warning.d.ts

I've been meaning to do this for a while, but I finally found the time.
Most of these changes are grammar changes from my API doc commit https://github.com/postcss/postcss/commit/56856ffa2553be0488d3358ae4de1b2a57b5e29d, but I also looked at each commit since the [5.0 release](https://github.com/postcss/postcss/releases/tag/5.0.0) and updated any relevant changes, making these type definitions in sync with the [5.0.4 release](https://github.com/postcss/postcss/releases/tag/5.0.4).
These type definitions are generated from a [TypeScript port of PostCSS](https://github.com/jedmao/postcss/tree/typescript), [complete with tests](https://github.com/jedmao/postcss/tree/typescript/test-ts), which can be found at [my typescript branch](https://github.com/jedmao/postcss/tree/typescript/lib-ts).

Update TypeScript definitions to 5.0.4 release

---

README.md

postcss-unmq removes media queries while preserving desktop rules for
IE≤8.

Add unmq plugin

---

.travis.yml

NodeJS v4 was just released [NodeJS v4 announcement](https://nodejs.org/en/blog/release/v4.0.0/). This updates the CI build script to accommodate the release.

Add Node.js 4.0 stable to Travis config

---

README.md

Missing back tick was causing the `and` to be in code block, not before or after :smile:

Add missing backtick to Readme and correct content quotes

---

lib/parser.es6

Some decision. But how to restore the space before semicolon? Does it need?
fix #566

Fix untrimmed decl.value

---

lib/parser.es6
test/parse.es6

Code changes from postcss/postcss-scss#8. Fixes postcss/postcss-scss#7

parse nested at-rules without trailing semicolon

---

README.md

This already happens to `cssnext`, so it seems appropriate.

README.md: use cssnano's homepage, instead of github repo

---

package.json

While people are using lower version of node, `Promise is not defined` error occured

add engine restriction since native Promise is used

---

README.md

All of these plugins are reasonably unique, and allow for the omitted edges using `*`. 
I am not including [`postcss-short-size`](https://github.com/jonathantneal/postcss-short-size) because it is very similar to `postcss-size`— the difference being that it allows one to omit the `width` or `height` value using `*`.

Adds unique short plugins

---

README.md

Add [`postcss-fallback`](https://github.com/MadLittleMods/postcss-fallback) to readme.
> PostCSS plugin to provide fallback values for properties without having duplicate declarations.
---
Input:
```css
.foo {
display: fallback(flex, inline-block);
width: fallback(45vh, 450px);
background-color: fallback(rgba(0, 0, 0, 0.5), #555555);
foo: fallback(bar, baz, qux, corge);
}
```
Output:
```css
.foo {
display: inline-block;
display: flex;
width: 450px;
width: 45vh;
background-color: #555555;
background-color: rgba(0, 0, 0, 0.5);
foo: corge;
foo: qux;
foo: baz;
foo: bar;
}
```

Add postcss-fallback to readme

---

docs/api.md

This was throwing me off while navigating the API docs.

Fix API links to LazyResult class section

---

README.md

Transform `start` and `end` properties to `left` and `right` depending on the writing direction of the document.

Added link to postcss-logical-properties

---

README.md

The biggest difference is that this pack doesn't include fallback plugins for IE9 or less.

Added level4 pack to README.md

---

README.md

[`postcss-raw`](https://github.com/MadLittleMods/postcss-raw)
> Protects nodes inside `@raw` at-rules from being touched by other plugins.
```css
@raw {
@import "variables";
$foo: #f00;
}
```

Add postcss-raw to plugin list

---

lib/previous-map.es6
test/previous-map.es6

Also, stop passing mappings:[] in tests -- that was source map rev. 2 syntax, and the source-map package doesn't support those.

Allow passing a previous map with no mappings (empty string)

---

docs/plugins.md

[Send PR to PostCSS README](https://github.com/totora0155/postcss-namespace/issues/1)
Like this.
```css
@prefix block;
.box {}
@prefix block2;
.box {}
```
Output.
```css
.block__box {}
.block2__box {}
```

Add postcss-namespace plugin to README

---

README.md

postcss-svg plugin does not correspond to guidelines:
- there are no tests,
- it's synchronous.

Replace postcss-svg with postcss-inline-svg

---

docs/plugins.md

[postcss-sorting](https://github.com/hudochenkov/postcss-sorting) is a plugin to sort rules content with specified order.

Add postcss-sorting to plugins list

---

docs/plugins.md

Add postcss-filter-mq to the optimizations area in readme.
Not sure if I put it in the right order.. doesn't seem absolutely alphabetical, so I placed it chronologically with the other `postcss-` prefixed plugins :grin:

add postcss-filter-mq to the optimizations area in readme

---

README.md

This is a common mistake.
Also, https://github.com/MoOx/postcss-cssnext/issues/251

Add a note in README about cssnext including autoprefixer

---

README.md

There was a [discussion going on at Gitter](https://gitter.im/postcss/postcss?at=56ac380ceaf741c118d5c7b6) that initiated this change.

Mention the PostCSS CLI in a more prominent place

---

docs/syntax.md

minor English tweak, replace `a` with `an`

Fix a typo

---

lib/tokenize.es6
test/tokenize.es6

I believe that the issue causing #727 is that the tokenizer was not registering newlines within strings. So whatever came after the string was thought to be on the same line as the string's opening --- which in this instance was not the case. 
I copied some logic from the tokenization of comments and verified that it works with a test. I also verified that the particular issue in #727 (the syntax error having a weird position) is fixed by this.

Track newlines within strings; fixes #727

---

docs/api.md
lib/node.es6
test/node.es6

Perhaps just an oversight from when I first implemented this method.
This change makes it easier to implement this feature - https://github.com/ben-eb/stylehacks/issues/4.

Allow options passing to Result#warn from Node#warn.

---

d.ts/at-rule.d.ts
d.ts/container.d.ts
d.ts/css-syntax-error.d.ts
d.ts/node.d.ts
d.ts/parser.d.ts
d.ts/postcss.d.ts
d.ts/processor.d.ts
d.ts/root.d.ts
docs/api.md
gulpfile.babel.js
postcss.d.ts

I recompiled [my typescript branch](https://github.com/jedmao/postcss/tree/typescript) with the newly-released [TypeScript 1.8.2](https://github.com/Microsoft/TypeScript/releases/tag/v1.8.2) and fixed the errors that popped up.
Also, TypeScript now supports a new `typings` field in the package.json file, which points to the type definitions for postcss. This is now the golden path and I like it very much compared to what we had before!

Update TypeScript support

---

docs/api.md

Remove extra dash.
It is generated without dash as you can see below.

Fix Root#toResult(opts) link

---

d.ts/postcss.d.ts

TypeScript compiler run with `tsc --noImplicitAny` prints:
`node_modules/postcss/d.ts/postcss.d.ts(26,19): error TS7006: Parameter 'css' implicitly has an 'any' type.`
Adding the `any` type explicitly fixes the error.

Fix missing type causing TypeScript compiler error with noImplicitAny.

---

lib/parser.es6
test/rule.es6

I ran into a strange bug while trying to fix this: https://github.com/stylelint/stylelint/issues/1148
Turns out the rule's `raws.between` seemed to have its tokens reversed. From the source code 
```css
a /*x*/
{}
```` 
I'd expect the rule's `raws.between` to be `" /*x*/\n"`. But instead I was getting `"\n/*x*/ "`.
I was able to reproduce this with a test in PostCSS. And I found what I think may have been a logic flaw in the `spacesFromEnd` function that is used to create `raws.between`. I adjusted that logic to get my test to pass, and all existing tests continue to pass. (The build failure seems to be related to code coverage reporting.)

Reverse token adding in spacesFromEnd

---

docs/plugins.md

Hello. I've created and polished [postcss-esplit](http://github.com/vitaliyr/postcss-esplit) plugin - and decided to add it to readme. 
The idea inside it that we were used in our project blesscss tool which just doing the same job. But it doesn't have support for source maps. Also we though to move our project to use postcss so I decided to wrote a plugin for postcss which would do just the same thing blesscss doing but with support of sourcemaps.
What do you think? 
(Duplicate pulls/806, but changes are in correct file)

Added postcss-esplit plugin

---

gulpfile.babel.js
package.json

This should resolve any issues with running the builds on different platforms.

Replace yaspeller command with gulp task

---

d.ts/postcss.d.ts

Example
```typescript
import { plugin, Container, Result } from "postcss";
export default plugin("postcss-test", function() {
return function(css: Container) {
const input = css.source.input;
console.log(input.css);       // haven't access to css property in typescript
// but valid in javascript
};
});
```

Update postcss.d.ts for Input interface

---

lib/map-generator.es6

Does it make sense to call `path.relative` when the input style does not have associated a path (eg it's `<input css 1>`)?
I'm not 100% sure about this fix, but in my brand new [PHP port of PostCSS](https://github.com/mlocati/postcss) the integration test with bootstrap.css (tokenize it and re-create it) has a huge performance improvement (about 2x fast)...

Avoid calls to path.relative when the input file name is not available

---

lib/css-syntax-error.es6
lib/terminal-highlight.es6

Before:
After:
See each commit for more details.
I also have a more crazy branch where I:
- Post-process the `tokens` array to create `,` tokens in some cases, to be able
to highlight some commas.
- Try to highlight property names, without false positives for pseudo-classes.
The code of that crazy branch is really ugly. I don't think it's worth it. Here's what it looks like:

Improve syntax highlight (sync with babel-code-frame)

---

lib/vendor.es6
test/vendor.js

#919
Support test cases `-1px -1px 1px rgba(0, 0, 0, 0.2) inset`

Fix `postcss.vendor.unprefixed` & `postcss.vendor.prefix`

---

docs/guidelines/plugin.md

As discussed on Gitter
Node 0.12 ends maintenance support at the end of this year. I think we should drop this requirement in the plugin guidelines and replace it by the active LTS, which would be an intemporal statement. Currently this means Node v4
I'm not sure if it is useful to update the boilerplate too, or let the plugin author decide which older versions of Node he wants to support.

remove Node 0.12 requirement in guidelines

---

docs/plugins.md

`postcss-parent-selector` adds a parent selector to the beginning of all rules.

added postcss-parent-selector to docs/plugins.md

---

docs/plugins.md

debugger.html from Firefox (the tool is [bundled and ship as firefox devtools](https://hacks.mozilla.org/2016/09/introducing-debugger-html/), its now a separate project hosted on github and can run on any browser) integrated `postcss` and `postcss-bidirection` plugin for bi-directional(RTL) support on different browsers.
https://github.com/devtools-html/debugger.html/pull/1419

add postcss-bidirection to plugins list

---

lib/postcss.d.ts

Sorry, @ai. I must not have copied over this one line properly, so I'm getting an error that postcss is not a function. Sorry about that.

Fix TypeScript module export

---

lib/css-syntax-error.es6

In the deprecation message associated with the `generated()` function, the word deprecation was spelled `depreacted`. This is incredibly minor, but it's something I've run into a fair amount of times recently when searching for `react` inside my library's bundle.

Fix typo in generated() deprecation message

---

package.json

To run postcss in the browser, the module _fs_ is required. With this addition we can tell webpack to ignore the _fs_ module.
This has been an issue before #830
https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module

Running postcss in the browser

---

README.md

I was able to get post-css working with Webpack 2 using this simple configuration (however, wasn't able to get post-css and webpack 2 working with the original instructions for webpack). 
Please feel free to confirm. Thanks!

add postcss setup instructions for webpack 2

---

docs/plugins.md

Hello!  I [created a new postcss plugin that allows for `@import` statements to work within nested css statements](https://github.com/eriklharper/postcss-nested-import).  I'd like to get this reviewed by the PostCSS community and also would like your help in determining why my tests are failing, which I think is due to how postcss processes the results, and not from a bug in my plugin code.  I used the PostCSS plugin boilerplate, so you can clone my project, run `yarn` and then `jest` to see the result of the test which looks like this:
```
FAIL  ./index.test.js
● replaces @import with the contents of the file being imported inside a declaration block.
expect(received).toEqual(expected)
Expected value to equal:
".vendor { background: silver; } .vendor-font { font-size: 14px; }"
Received: …
```

postcss-nested-import

---

docs/plugins.md

This is my first _from scratch_ plugin that I built today all day long!
> [PostCSS](https://github.com/postcss/postcss) plugin that let you control your layout (`ltr` or `rtl`) through logical rather than direction / physical rules.
- [Postcss-plugin-boilerplated](https://github.com/postcss/postcss-plugin-boilerplate) was used
- [Postcss-plugin-guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md) were followed
- Yarn was used as dependency manager
- Travis is being used as CI service
- The plugin itself has 100% coverage with Jest.
- It is published on [npm](https://www.npmjs.com/package/postcss-start-to-end)
- I'm trying to add [Coveralls](https://coveralls.io/github/sandrina-p/postcss-start-to-end) as coverage reporter, but I'am having troubles.
Thank …

Add Plugin postcss-start-to-end

---

lib/postcss.d.ts

This PR enables type guards on the `type` property of `Node`.
```ts
function doSomethingWithNode(node: postcss.Node): string {
switch (node.type) {
case 'root':
// node is inferred as Root here
node.toResult();
return 'root';
case 'atrule':
// node is inferred as AtRule here
node.params = '';
return 'atrule';
case 'rule':
// node is inferred as Rule here
node.selector = '';
return 'rule';
case 'decl':
// node is inferred as Declaration here
node.important = false;
return 'decl';
case 'comment':
// node is inferred as Comment here
node.text = '';
return 'comment';
// default is not necessary as TypeScript knows the above cases are collectively exhaustive
}
}
```
Additionally, the `parent` property of `Root` is altered from `Container` to `void`, as it "Should always be undefined for a Root …

Improve postcss.d.ts so that type guards work

---

docs/plugins.md

This plugin is like postcss-uncss, but more simple, because it uses Cheerio to parse static HTML strings instead of loading a page and its resources with PhantomJS.

Add postcss-html-filter to plugins list

---

docs/plugins.md

PostCSS plugin to replace output file names with HASH algorithms (md5, sha256, sha512, etc) and string length of your choice - for cache busting.

Add postcss-hash plugin

---

lib/postcss.d.ts

The `declare module "foo"` syntax is used to declare values ambient types for other modules. When declaring types for your own module you're supposed to just use `declare` for each exported member individually. Which for postcss isn't that many because it's mostly in a namespace.
The reason this is important is that the syntax being used currently can cause problems with typescript projects that resolve to several different versions of postcss because of the `export =` is a global in typescript and causes a conflict between the several implementations of the `declare module` blocks. or something. I don't know. This seems to work for me, but I think it will require a 5.x release to fully address the issue. At least this is what the typescript experts I know have told me.

use declare instead of declare module

---

lib/parser.es6

Fixes https://github.com/postcss/postcss/issues/1066 . 
As was discussed, if comment does not have at least space from one of side interp it as a part of word.
> Note,  some of `postcss-parser-tests` should be updated as them match old parsing rules.

Fixed selector parsing with comment inside

---

docs/plugins.md

Not entirely sure where this should go, or if it should be listed at all. It's technically shimming a future CSS spec but the shim provided isn't advanced enough to be a 'set and forget' kind of thing. 
Still a useful shim IMO, as long as users understand its (severe) limitations.

Add postcss-subgrid to plugins list

---

docs/plugins.md

A plugin for joining conflicting transition declarations into a single declaration. Useful when you're using classes or mixins for simple transitions and want to stack them for certain elements.

Add postcss-join-transitions to plugins list (#1135)

---

docs/plugins.md

Submitting a new PostCSS plugin for your approval. This is based off a Sass mixin that I used a lot. It generates and rem based font-size and line-height from a number value. The plugin also generates a px fallback for older browsers. So for fontsize: 16, the plugin will generate the following:
{ font-size: 16px;line-height: 24px;font-size: 1rem;line-height: 1.5rem; }

Added postcss-fontsize to plugins list.

---

lib/postcss.es6

`css` doesn't exist in this example, but `root` does.

docs: fix .plugin parameter reference

---

lib/node.es6
package.json

ESlint required an `@return` for JSDoc comments, so I had `cleanRaws` return itself like some other functions for chaining.

Update clone and cleanRaws docs

---

lib/container.es6

We can delete last `else` because this no necessary.
For example, if we have code like this:
```javascript
if (typeof child === 'number') {
return child
} else {
return this.nodes.indexOf(child)
}
```
And variable `child` has type `number` then the function always return `child` and never goes on the lines after if-statment. So we can delete `else`-branch:
```javascript
if (typeof child === 'number') {
return child
}
return this.nodes.indexOf(child)
``` 
I think this part of code more readable then first one.

Refactoring. Delete unnecessary else with return

---

lib/tokenize.es6
test/tokenize.test.js

This PR stems from [an issue in postcss-less](https://github.com/shellscape/postcss-less/issues/117) and a [short discussion on twitter](https://twitter.com/sitnikcode/status/1044319395760263168) with @ai.
PostCSS v7 has a wonderful parser class structure that enabled syntaxes to be created by inheriting from the base `Parser` class and selectively overriding methods to handle syntax nuances - all _without having to reimplement a parser or tokenizer._ That's a **massive** advantage to developers. However, there are some strict rules hardcoded into the tokenizer. Because the tokenizer is optimized for performance, it cannot be made a class to be inherited from. A mechanism is then needed to work around/with the hardcoded tokenizer rules.
In some situations it would be preferable to fetch …

feat: add ignoreUnclosed option to nextToken method

---

lib/postcss.d.ts

By including an index signature, the `ResultMessage` interface becomes more extensible. Plugins are allowed to push messages that have properties besides the few that are already defined.
In fact, the only ones that are now specified explicitly are those that are required. This includes `plugin`, which previously was not marked required. However, the [API documentation guides users](http://api.postcss.org/Result.html#messages) to always specify both `type` and `plugin`.
cc @jedmao 
---
Before this change, the following code would produce an error:
```typescript
// Object literal may only specify known properties, and 'file' does not exist in type 'ResultMessage'.
result.messages.push({
type: 'dependency',
plugin: 'postcss-foo',
file: '/some/path/to/dependent.css',
parent: …
```

updates ResultMessage interface with an index signature

---

lib/postcss.d.ts

TransformCallback's result argument shouldn't be undefined. Also the return type could use some clarification.
fixes #1213

Fixes TransformCallback type definition

---

lib/postcss.d.ts

the type definitions are updated to reflect where properties are optional. the comments are used to clarify the conditions in which those properties will have values, or not.
fixes #1214
i also took this opportunity to improve on #1215's work by adding a clarifying comment, as mentioned at the end of [this comment](https://github.com/postcss/postcss/issues/1213#issuecomment-451367502)

Updates Node#source to optional type, adds comments

---

lib/postcss.d.ts

It seems that quite a few of the type definitions related to `ProcessOptions` were not in sync with the latest source. This change should bring it back up to date.
Notably:
*  `ProcessOptions` no longer extends `Syntax`. This used to be a way of saying the object had both `parse` and `stringify` options, but that wasn't true. The object does have `parser` and `stringifier` options.
*  The `safe` option was removed. It's not referenced in the [documentation](http://api.postcss.org/global.html#processOptions).
*  `Parse` and `Stringify` are renamed to `Parser` and `Stringifier`. This is consistent with the documentation, and reflects the fact that these are functions (verbs instead of nouns).
*  `Parser` options has `from` and `map` properties, instead of taking `SourceMapOptions` (which is …

Updates type definitions for ProcessOptions

---

docs/plugins.md

PostCSS plugin that shortens CSS class names to optimize website performance.
https://github.com/mbrandau/postcss-class-name-shortener
https://www.npmjs.com/package/postcss-class-name-shortener

Add postcss-class-name-shortener to docs/plugins.md

---

lib/map-generator.es6
test/browser.test.js
test/map.test.js

There was a bug where end node parts (not sure how they're actually called) like ";" or "}" had off-by-one-errors (explanation in separate comments)
[Before](http://sokra.github.io/source-map-visualization/#base64,CmJvZHkgewoJYmFja2dyb3VuZC1jb2xvcjogcmVkOwp9Cgo=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9zdHlsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBO0NBQ0Msc0JBQXNCO0NBQ3RCIiwiZmlsZSI6Im91dC5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyJcbmJvZHkge1xuXHRiYWNrZ3JvdW5kLWNvbG9yOiByZWQ7XG59XG5cbiJdfQ==,CmJvZHkgewoJYmFja2dyb3VuZC1jb2xvcjogcmVkOwp9Cgo=)
[After](http://sokra.github.io/source-map-visualization/#base64,CmJvZHkgewoJYmFja2dyb3VuZC1jb2xvcjogcmVkOwp9Cgo=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9zdHlsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBO0NBQ0MscUJBQXFCO0FBQ3RCIiwiZmlsZSI6Im91dC5jc3MiLCJzb …

Fix end tokens having wrong sourcemap entry

---

lib/map-generator.es6

Fixup for #1223:
> But I discovered an issue: the last semicolon might be missing, then [this](http://sokra.github.io/source-map-visualization/#base64,Cgpib2R5IHsKCWNvbG9yOiByZWQ7CgliYWNrZ3JvdW5kLWNvbG9yOiByZWQKfQoK,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9zdHlsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7QUFFQTtDQUNDLFVBQVU7Q0FDVixvQkFBb0I7QUFDckIiLCJmaWxlIjoib3V0LmNzcyIsInNvdXJjZXNDb250ZW50IjpbIlxuXG5ib2R5IHtcblx0Y29sb3I6IHJlZDtcblx0YmFja2dyb3VuZC1jb2xvcjogcmVkXG59XG5cbiJdfQ==,Cgpib2R5IHsKCWNvbG9yOiByZWQ7CgliYWNrZ3JvdW5kLWNvbG9yOiByZWQKfQoK) happens (the last `d` of `red` is separate).
> Area there other cases where something similar might happen?

Sourcemaps fix for optional semicolon

---

docs/plugins.md

new plugin for converting classes to mixins in Sass, Less and Stylus! 
see repo for more info: https://github.com/nrkno/postcss-classes-to-mixins

add postcss-classes-to-mixins

---

lib/tokenize.es6
test/tokenize.test.js

Exposes a `position` function returned from the tokenizer upon creation. This allows one to get the character the tokenizer is currently at.
Closes #1236

Expose Tokenizer `position` function

---

.travis.yml
lib/parser.es6

Add processing to the valid user-defined variables

---

lib/postcss.d.ts

`Rule.selectors` is guaranteed to be an array. The array itself _may_ be empty.
https://github.com/postcss/postcss/blob/d245ada946919df91009fd1745a7075bf5e84e43/lib/rule.es6#L22-L40
https://github.com/postcss/postcss/blob/d245ada946919df91009fd1745a7075bf5e84e43/lib/list.es6#L12-L53

fix(types): make `Rule.selectors` non-optional

---

lib/postcss.d.ts

I've made several changes to the typescript definitions, outlined below:
* I removed the Stringifier class definition. I expect this one might be controversial, however, I believe the point of these typescript definitions are to export the types which are accessible _externally_. The Stringifier class was defining the _internal_ shape of the Stringifier class. There's no way to access that class and its members externally since it is not exported, nor is it returned by any function that is exported. Instead, the external postcss API only requires that a "stringifier" be a function which takes two arguments, a node and a builder, and returns nothing. There's no other external requirement on the implementation details of the stringifier, so, the class definition is not needed. Additionally, …

Updated typescript definitions

---

docs/plugins.md

postcss-simple-trig
https://github.com/Rplus/postcss-simple-trig
> A PostCSS plugin to calculate trigonometric functions: sin/cos/tan

Add postcss-simple-trig to list

---

README.md

Update `README.md` to not tout Parcel's implementation as "perfect". There are [the several issues in Version 1](https://github.com/parcel-bundler/parcel/labels/CSS%20Preprocessing). And [Version 2](https://github.com/parcel-bundler/parcel/projects/5) is not out yet to possibly fix the issues via [issue #2157](parcel-bundler/parcel#2157).
I am amenable to any alteration of this edit. Perhaps, the change should be _only_ to remove the word "perfect". But, Parcel's implementation has been flawed for a long time.
_I provide the extra information, in hopes of saving someone else from believing Parcel will manage PostCSS for them. Three times over this and the past years, I have crawled out of the maze of Parcel & PostCSS rabbit holes to decide that it is _still_ better for a project to …

Update README.md claim of "perfect" Parcel support

---

.travis.yml
appveyor.yml
package.json
yarn.lock

Dev dependency  `jsdoc` is updated to avoid crash in node 12. (https://github.com/jsdoc/jsdoc/blob/master/CHANGES.md)
Node 11 in CI  is changed to node 12.

chore(ci): add node 12 and remove node 11 in ci

---

lib/postcss.d.ts

Setting `annotation: true` has a different behaviour to omitting the `annotation` key, but this is not allowable by the type system. 
This PR fixes this, so that `annotation: true` is an allowed option.

correct type for `annotation`

---

docs/plugins.md

Adds [postcss-font-format-keywords](/valtlai/postcss-font-format-keywords) to the *Future CSS Syntax* section.

Add plugin to list

---

lib/input.es6

On windows, when calling `postcss.parse` providing it with a posix-style absolute file path (e.g. running against an in-memory fs) leads to the `from` field being resolved to a windows-style path.
For example, the file from path `/a/b/c` gets resolved to `C:\\a\\b\\c`, which doesn't exist in my case.

parse: avoid re-resolution of "already absolute" file paths

---

docs/plugins.md

[`postcss-sort-media-queries`]:    https://github.com/solversgroup/postcss-sort-media-queries
[`postcss-momentum-scrolling`]: https://github.com/solversgroup/postcss-momentum-scrolling
Adding momentum style scrolling behavior (`-webkit-overflow-scrolling:touch`) for elements with overflow (scroll, auto) on iOS.
Combine and sort CSS media queries with mobile first or desktop first methods

Add plugins: postcss-momentum-scrolling, postcss-sort-media-queries

---

docs/plugins.md

postcss-viewport-height-correction solves the popular problem when 100vh doesn’t fit the mobile browser screen.

Added postcss-viewport-height-correction

---

lib/postcss.d.ts

This can return false if no origin is available.

Update the type annotation for Input.origin

---

lib/node.js
lib/parser.js
lib/tokenize.js
package.json
test/tokenize.test.js

https://cultofmartians.com/tasks/postcss-offset.html#task
#1325 
As I can see those changes also require [test fixtures](https://github.com/postcss/postcss-parser-tests/tree/master/cases) and [documentation](https://github.com/postcss/postcss/blob/master/docs/architecture.md) update.

Tokenizer: update token structure

---

lib/input.es6

Was compiling through ng-packagr and got the following errors. Looks like `css` is undefined at the time this bit of code was reached and the `toString` existence check fails.
Error after this PR:

fix(input): undefined check in addition to the null check

---

lib/node.js
test/node.test.js

Consider an AST where a node `root` has child nodes `[a, b, c]` and there are other nodes `d` and `e`. `a.replaceWith(a, d, e)` now results in `root` having the children `[a, d, e, b, c]`.

Allow replaceWith to be called with input that includes itself.

---

docs/plugins.md

Thanks for your great postcss project and I wrote a unified deep scoped style postcss plugin for vue, which can be used to transfrom those deep selectors in less/scss/sass to unified selector of Vue. I wish it can do some help for Vue users. And this time I add some Input/output examples, Thanks.

Add postcss-deep-scopable

---

lib/postcss.d.ts
lib/processor.d.ts

This PR adds the missing `Transformer` import to the `processor.d.ts`. The `processor.d.ts` references the `Transformer` interface for the [`plugins`](https://github.com/postcss/postcss/blob/bdd34bda76baa651550fedb7c07c054abb8256bb/lib/processor.d.ts#L41) field. However, this interface is never imported.
Couple of interesting things about this change:
- VSCode doesn't automatically surfaces this missing `Transformer` type and instead resolves it `Transformer` type exposed by [`lib.dom.d.ts`](https://github.com/microsoft/TypeScript/blob/a960463cf3ae379b670e0e3154445d9392c9b667/lib/lib.dom.d.ts#L1814). Adding `lib: []` to the `tsconfig.json` does make VSCode error out on the missing type.
- I don't understand why `check-dts` has not picked this up.

Add missing Transformer type to processor.d.ts

---

lib/previous-map.js
lib/symbols.js
test/css-syntax-error.test.ts
test/processor.test.ts

Related with https://github.com/postcss/postcss/issues/1430#issuecomment-701043034
I've added some changes in the way that some modules are imported, to ease the automatic transformation to Deno that I'm doing here: https://github.com/oscarotero/postcss-deno

Code style changes to Deno port

---

lib/comment.d.ts

I believe `right` of the CommentRaws interface should be of type `string` instead of `boolean`

Fix CommentRaws interface right type

---

.github/workflows/deno.yml
README.md

Related #1430 
I've created the new repository [postcss-deno](https://github.com/postcss/postcss-deno) containing a script to get the postcss code and transform to javascript compatible with Deno.
This PR add a github action that is runned after creating new tags, so it will update automatically the code in the postcss-deno repository and create the same tag there.
The only requirement is a secret variable with a [PAT](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) that have writting access to postcss-deno repository in order to commit the changes and create the new tag. So, after merging this PR, you have to:
- Go to Settings > Secrets of this repository
- Click in "New Secret"
- The secret name is `PAT`, and the value …

Add support for Deno

---

lib/postcss.d.ts

Hello, I noticed "comment" was missing from the types when trying to `import { comment } from "postcss";`.
This PR adds the missing type and reorders the types to match the javascript file.

Add missing "comment" export in types + reorder

---

lib/at-rule.js
lib/comment.js
lib/container.js
lib/css-syntax-error.js
lib/declaration.js
lib/input.js
lib/lazy-result.js
lib/list.js
lib/node.js
lib/parse.js
lib/postcss.js
lib/previous-map.js
lib/processor.js
lib/result.js
lib/root.js
lib/rule.js
lib/stringify.js
lib/warning.js
tsconfig.json

This is done by assigning the property `default` for all properties that are exported using `export default` according to their type definitions.
Closes #1424

Fix usage of default exports with TypeScript

---

lib/lazy-result.d.ts
lib/lazy-result.js
test/lazy-result.test.ts
test/types.ts

Hi, following our Gitter chat yesterday, I've learnt `LazyResult` was meant to implement the `Promise` contract.  This pull request adds the [[Symbol.toStringTag] property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) to `LazyResult` which Typescript requires to type something as a `Promise`. 
* Explicitly implement Promise<Result> in the type declaration
* Add mising [Symbol.toStringTag] property
* Add some type tests to ensure we can type `postcss(plugins).process` results

fix(typescript): ensure LazyResult complies with Promise interface.

---

lib/lazy-result.d.ts

This change is motivated by the ability to patch `Promise` prototype globally in both code and types. This change helps to avoid such behavior.
Though I think monkey patching prototypes is a terrible practice one cannot alway control the code of all their dependencies or the platform that is being developed on top of. Hopefully this change can help to ease the pain of working with such things.

Improve LazyResult type

---

.github/workflows/deno.yml

- Updated the Deno environment setup to the latest version
- Removed the copy commands because those files are already copied by the js script.

Fixed Deno conversion workflow

---

.github/workflows/deno.yml

Allow access to environment variables on deno test

---

lib/fromJSON.js
lib/node.js
test/fromJSON.test.ts
test/node.test.ts

I've found two problems related to `Input`:
1std and 2nd commit: I missed that all nodes have a `source` property, not just the root (this caused stringification to fail)
3rd commit: More of an optimization: because of 1), the source contents & map would be stored once for every node (!). This has something like a quadratic memory usage because larger CSS files have more files, so with 10x more rules, the CSS source is about 10x larger and is stored 10x times.
I've instead deduplicated these inputs objects by replacing `node.source.input` with a number in the `toJSON` output and including a `_inputs` array which maps number to input object (because most of these are `===`-equal). This is then reversed in fromJSON. This breaks a buch of `postcss-parser-tests` tests at the moment though. …

Fixup JSON AST conversion

---

lib/postcss.d.ts
test/postcss.test.ts
test/processor.test.ts

Returning a a `Processor` instance from a plugin creator (function with `postcss = true`) already works in practice, and was supported with PostCSS 7 plugins, but TypeScript types do not allow it. This updates the types and adds a test. 
Support 'plugins of plugins' like cssnano (https://github.com/cssnano/cssnano/pull/961) or postcss-modules. These 'meta-plugins' take some options, build a list of plugins, create a `Processor` and run `process()` over the AST. The issue is that in PostCSS 8, this does not notify visitor plugins, forcing these 'meta-plugins' to run as `OnceExit`. This pull request would allow to return a `Processor` instance instead of calling `process()` inside the 'meta-plugin'.
1. Keep using `OnceExit()` with a separate `process()`. This means 'meta-plugins' and all …

Proposal: change plugin creator type to allow returning a processor.

---

README.md
docs/plugins.md

Add avif-in-css and webp-in-css image plugins

---

lib/stringifier.js
test/stringifier.test.js

Fixes #1494 
I had a search around your codebase and it doesn't look like anything used `Stringifier#root` as a property. so i just removed the line. if you'd rather have it renamed, let me know
it was overwriting the `root(node)` method previously, which was clearly wrong and caused issues with nested roots.
cc @ai

remove root assignment in stringifier

---

lib/css-syntax-error.d.ts
lib/root.d.ts
test/root.test.ts
test/types.ts

Spotted in VS Code that some code is not used. Then enabled [`@typescript-eslint/no-unused-vars`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md) to catch everything.

Remove unused code

---

docs/plugins.md

postcss-auto-rem will compile px to rem.
smart-rem will set the value of the HTML root element property fontsize automatically.

Update plugins.md， add plugin postcss-auto-rem

---

README.md

Potentially related to #1457 and #1370
This stemmed from me using the JS API in a script and getting the following error output:
```
node:internal/process/promises:227
triggerUncaughtException(err, true /* fromPromise */);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator
at Object.writeFile (node:fs:1482:5)
at /Users/.../build-css.js:46:12
at processTicksAndRejections (node:internal/process/task_queues:93:5) {
code: 'ERR_INVALID_ARG_TYPE'
}
```

add .toString() on writeFile for JS API example

---

lib/postcss.js
test/postcss.test.ts

Adding the plugin name to the deprecation message to help people debug which plugin needs to be upgraded.  
Translated string is from my friend who can read/write Chinese but only conversation, doesn't use it on a technical basis, so a proofread would be appreciated.

fix: add plugin name to deprecation message

---

docs/plugins.md

A plugin which define custom css units and convert them to CSS variables.

Add post-custom-css-units

---

lib/list.js
test/list.test.ts

I ran into this in practice when cssnano converted a quoted attribute
selector (which contained a comma) to use backslash escapes instead.

Don't split on escaped characters in list.split()

---

package.json

Compiling `postcss` in webpack 5 will cause an error due to the removal of automatic node built-in polyfills. 
This change tells webpack to ignore the `path` module when compiling, the same treatment `fs` already receives. I have successfully run `postcss` in webpack 5 with this change. 
This issue was raised in #1509
Resolves #1509
Example error:
```
ERROR in ./node_modules/postcss/lib/previous-map.js 4:24-39
Module not found: Error: Can't resolve 'path' in '/Users/person/some-project/node_modules/postcss/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

Ignore path module for browser builds

---

lib/input.js
lib/map-generator.js
test/browser.test.ts

I've also fixed the browser tests as they were not mocking correctly. Calling `doMock` after importing `postcss` had no effect as the module had already been processed before the mock takes effect.

Handle empty path object in browser builds

---

docs/plugins.md

This PR adds the PostCSS Blurry Gradient Workaround to the plugins list.

Add PostCSS Blurry Gradient Workaround plugin

---

docs/plugins.md

I just published a new plugin, [`postcss-multi-value-display`](https://github.com/jake-low/postcss-multi-value-display), which transforms [CSS Display Module Level 3](https://www.w3.org/TR/css-display-3/) multi-value syntax into legacy single-value equivalents when such equivalents exist. The plugin can be installed [from NPM](https://www.npmjs.com/package/postcss-multi-value-display).
This PR adds a link and short description of that plugin to postcss/docs/plugins.md. I also fixed a couple of alphabetization issues in the "Future CSS Syntax" section (though looking again I see that I didn't catch them all).

Add postcss-multi-value-display to plugins.md

---

lib/postcss.d.ts

This will simplify the types import for `postcss-values-parser`: https://github.com/shellscape/postcss-values-parser/pull/132

Export types for NodeErrorOptions

---

README.md

The current Deno example did't work. I created [this issue](https://github.com/postcss/autoprefixer/issues/1402).
Here is an announcement about the url change: https://jspm.org/jspm-dev-release

Fix import url for Deno example

---

lib/input.js
lib/map-generator.js
package.json

I think that the browser field is missing `url: false`.
I'm not completely sure that this is the right fix and also the npm package `url` does not implement the APIs used by postcss. 
steps to reproduce
```
mkdir postcss-browser 
cd postcss-browser 
mkdir src
echo 'import "postcss";' > src/index.js
npm init -y
npm install webpack webpack-cli postcss
npx webpack
```
This will emit error: 
```
ERROR in ./node_modules/postcss/lib/input.js 3:39-53
Module not found: Error: Can't resolve 'url' in 'C:\projects\postcss-web-bundle\postcss-browser\node_modules\postcss\lib'
```

Fix browser bundling with webpack 5

---

lib/previous-map.js

Fix Strategy: Replace `(.*)` with `(?:(?!sourceMappingURL=).)*`

Fix ReDoS in previous-map

---

lib/input.js
lib/map-generator.js
lib/previous-map.js
package.json

Since `path` is false in browsers build the `source-map` package is actually not in use*.  
This PR adds `"source-map": false` to the `package.json` also added explicit protection for the existence of the `source-map` API's.
Now if one will want to use postcss in browser and support source maps he will need to include `path` and `source-map` packages
This will decreased the bundle size of postcss by ~27% (from 29KB to 21KB)
(*) There is only one feature that I wasn't sure what to do with related to `fromJSON`. It is using the `PreviousMap` (no problem there) and `PreviousMap` uses the `source-map` package and I wasn't sure how to fallback. It might be a super edge case for browsers.

Remove source-map from browser build

---

docs/guidelines/plugin.md
docs/guidelines/runner.md
docs/writing-a-plugin.md

As discussed in #1537 this pull request adds documentation for a new `dir-dependency` message type that can be used to signify that a plugin depends on the contents of a directory. This would be used in the same way as the `dependency` message but with a `dir` property instead of a `file` property:
```js
result.messages.push({
type: 'dir-dependency',
plugin: 'postcss-import',
dir: '/js',
parent: result.opts.from
})
```
Runners should watch this directory for changes and rebuild the CSS when something changes.
This PR also adds some documentation for the existing `dependency` message to the plugin and runner guides, and clarifies the usage of dependency messages in the "Writing a PostCSS Plugin" documentation.

Add `dir-dependency` documentation

---

lib/at-rule.d.ts
lib/comment.d.ts
lib/declaration.d.ts
lib/node.d.ts
lib/node.js
lib/root.d.ts
lib/rule.d.ts
test/node.test.ts

This PR adds an `assign` method to all nodes, allowing authors to assign multiple properties to a node from a single object.
```js
decl.assign({ prop: 'word-wrap', value: 'break-word' })
```
This can improve code clarity when updating multiple properties while offering a helpful typing experience.

Add assign method to Nodes

---

lib/map-generator.js
lib/postcss.d.ts
lib/previous-map.d.ts
lib/previous-map.js
package.json
test/lazy-result.test.ts
test/map.test.ts
test/previous-map.test.ts
yarn.lock

I made the fork from source-map and named it [source-map-js](https://www.npmjs.com/package/source-map-js). It contains several performance optimizations. Now source-map consumer should be 4x faster.
PR with optimizations: https://github.com/7rulnik/source-map/pull/2
Reasons and difference of fork: https://github.com/7rulnik/source-map#difference-between-original-source-map

Use source-map-js (source-map's fork) 

---

docs/guidelines/plugin.md
docs/guidelines/runner.md

As discussed in #1585 this pull requests adds documentation for an optional `glob` property for `dir-dependency` messages. This property can be used to indicate which files within a directory a plugin depends on:
```js
result.messages.push({
type: 'dir-dependency',
plugin: 'postcss-import',
dir: '/imported',
glob: '**/*.css',
parent: result.opts.from
})
```

Add `glob` message property documentation

---

lib/parser.js
test/parse.test.ts

I've added some test-cases to ensure it works.
Also added a comment about `why` we it need to get token[3]+1
And ultimately it resolves https://github.com/postcss/postcss/issues/1617
Regards,
Gusted

Return correct column on `missed semicolon`

---

package.json

It's useful for contributors who've cloned the repo to type `npm bugs` to launch GitHub Issues for this project. :-)
REF: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bugs

Add bugs field to package.json

---

README.md

A fresh install of postcss and precss throws this error:
> Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.6, but precss uses 7.0.36.
Precss seems to be no longer maintained, and I suggest removing it from the Readme. [Last commit](https://github.com/csstools/precss/commits/master) was 3 years ago.

Remove unmaintained precss plugin from Readme

---

docs/plugins.md

`postcss-prefix-hover` is a plugin for adding a prefixed selector to any selection containing `:hover` e.g. changing `.foo a:hover {}` to `.using-mouse .foo a:hover {}`

Add postcss-prefix-hover to list of plugins

---

docs/README-cn.md
docs/plugins.md
lib/processor.d.ts

The precss plugin appears to be unmaintained, and does not support newer versions of PostCSS.
[References to precss were removed from the Readme back in August.](https://github.com/postcss/postcss/commit/e924aa05004ca1de91ddf06963734fadf4cc3c5f) But I forgot to search the repo for any other references, so this PR finishes removing/replacing other references to that plugin.
`docs/plugins.md` already has `postcss-nested` listed.
I did not add `postcss-nested` as a replacement in `docs/README-cn.md` as I don't know the language.

Remove remaining references to unmaintained precss

---

docs/plugins.md

`postcss-opacity-percentage` is a plugin for transforming a CSS4 percentage-based `opacity` value to the more supported float-based value (e.g. `opacity: 75%;` ➡️ `opacity: 0.75;`).

Add postcss-opacity-percentage to list of plugins

---

lib/css-syntax-error.d.ts
lib/css-syntax-error.js
lib/input.d.ts
lib/input.js
lib/node.d.ts
lib/node.js
lib/parser.js
lib/warning.d.ts
lib/warning.js
test/css-syntax-error.test.ts
test/node.test.ts
test/previous-map.test.ts
test/warning.test.ts

Context: https://github.com/stylelint/vscode-stylelint/issues/315, https://github.com/stylelint/stylelint/issues/5694
Allows for better diagnostics in linters, language servers, and plugins.
Currently, since only single positions are supported, this means that downstream, when we display errors in different tools, in my particular case, a language server and editor integration, we can only display a single position as part of the error, even when the error pertains to more than just one character.
These changes allow warnings and errors to be emitted with an additional `endLine` and `endColumn` which pertains to an end position, exclusive, of the problem. It also adjusts CSS syntax errors to always provide an end position for consistency. With these additions, we would be able to better …

feat: Support ranges for errors and warnings

---

lib/postcss.d.ts
lib/result.d.ts

Fixes #1667
A `Result` can now contain a root which is ` Document`. For example, a
custom syntax may produce a `Document` containing several nested `Root`
stylesheets.
Similarly, the default type parameter of `Parser` has been updated to
include `Document` since custom syntaxes must account for this anyway.
FYI the casts in the tests shouldn't reduce our test accuracy, since if the type was anything which doesn't cross over with `Root`, typescript would complain.

fix: add `Document` to result sets and default parser type

---

package.json

Running `./script.js` doesn't work on Windows, only `node ./script.js` does. This patch updates the test script so that it works on Windows as well as on other platforms.

fix: make test script work on windows

---

lib/stringifier.d.ts
lib/stringifier.js

Fixes #1673 
Some of the methods have `undefined` in the return type because of this pattern:
```ts
let value; // undefined at this point
root.walk((n) => {
if (n.something) {
value = n.something;
}
});
return value;
```
which would mean `value` can sometimes be undefined (if `something` was never found).
let me know if you want me to update the JS to have a default value

fix: add stringifier type definitions

---

docs/plugins.md

Adds the `postcss-rem-to-px` plugin to the docs.
This seems to be the only plugin that correctly converts negative values as well.

docs: :memo: Add plugin to docs

---

lib/stringifier.d.ts

@ai is there any chance we can get some kind of hotfix release out for 8.4?
i was an idiot and exported the stringifier named, rather than as a default... it is actually a default export 🤦‍♂️

fix: export stringifier as a default

---

README.md

To use PostCSS with Svelte, you must install the preprocessor which first converts PostCSS syntax into regular CSS so that the Svelte compiler can handle it

[docs] add link to Svelte preprocessor

---

docs/plugins.md

This pull request adds [postcss-rtlcss plugin](https://github.com/elchininet/postcss-rtlcss) to the plugins list.

Adds postcss-rtlcss plugin to the plugins list

---

lib/at-rule.d.ts
lib/comment.d.ts
lib/declaration.d.ts
lib/rule.d.ts

Fixes #1691 
These didn't have extensible raws before:
- at-rule
- comment
- declaration
- rule
I've also used `unknown` here, as a way to push consumers to type check before usage. if you'd rather have `any`, let me know and i will change it.

fix: allow all `raws` to be extended

---

docs/plugins.md

A new plugin that provides a function to retrieve design tokens expressed in JS or JSON, within CSS.
I added this as per the instructions on https://github.com/postcss/postcss-plugin-boilerplate

Add postcss-design-tokens plugin

---

lib/node.d.ts

I think `Node#warn()` should return `Warning`, not `void`:
https://github.com/postcss/postcss/blob/8718e0656e78f96d7812300bc372ff3a574d6fad/lib/node.js#L70-L74

Fix `Node#warn()` return type

---

lib/container.js
test/visitor.test.ts

Fixes #1738
I wasn't quite sure where to put the test but the gist of the issue is that
1. `node.append` calls `node.normalize`
2. `node.normalize` sets the parent to `this`.
The problem arises when `node` is a proxy. This means that `this` ends up being a proxy instead of the raw node. Assigning the proxy to the "raw" child node's parent has a side-effect of causing `proxyOf.nodes` to contain proxies rather than raw postcss nodes.
This causes `indexOf` lookups to fail since they're sadly not transparent to Proxies b/c of object identity.
Later on `append` tries to use this index assuming that the nodes passed in are definitely children and have been found and crashes.
I'm not 100% sure this is the right fix because the interactions just to get this to happen are fairly specific. Change …

Fix `append()` failing after mutating nodes through .parent

---

lib/postcss.js
test/postcss.test.ts
test/processor.test.ts

I use some CJS package and I import from its index.js the functionality I need, however it also exposes an old postcss plugin. I don't use it, so I think it makes more sense to print a warning only when the plugin is actually used. I also added a check to preserve behavior that the warning is being printed only once.

fix: print deprecation warning only when plugin is used

---

README.md

This pull request replaces two unmaintained plugins on the favorite plugin list:
* `postcss-assets` by `postcss-url`
* `postcss-rtl` by `postcss-rtlcss`

Replace two unmaintained plugins on README

---

README.md

Looks like `mhmadhamster` unplublished the `postcss-language` extension.
> https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language
So replace it with [csstools.postcss](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) .. cc @ai

chore: update vscode extension infomation

---

test/container.test.ts

In [`@csstools/postcss-cascade-layers`](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-cascade-layers/src/sort-root-nodes.ts#L73) we use `container.nodes.sort(...)`.
I noticed that there weren't any tests for this.
Maybe we are using it wrong and should use a different way to sort nodes?

add test for sorting container.nodes

---

lib/container.js
test/container.test.ts

see : https://github.com/postcss/postcss/issues/1778
Current context :
1. call `insertAfter(exist, existingSibling)`
2. set the value of `exist` to the index of the node in `this.nodes`
3. call `this.normalize()`
4. `this.normalize()` removes `existingSibling` from it's parent. (which is `this`)
5. `exist` is still the pre-calculated index
6. `this.nodes` has changed and the indices have changed because `existingSibling` was removed from it's parent
7. 🔥  
```js
insertAfter(exist, add) {
exist = this.index(exist)
let nodes = this.normalize(add, this.proxyOf.nodes[exist]).reverse()
for (let node of nodes) this.proxyOf.nodes.splice(exist + 1, 0, node)
let index
for (let id in this.indexes) {
index = this.indexes[id]
if (exist < index) {
this.indexes[id] = index + nodes.length
}
} …
```

recalculate the insertion index after normalizing a node

---

lib/container.js
test/container.test.ts

I missed one instance of `exist` vs `existIndex` : https://github.com/postcss/postcss/pull/1781/files#diff-f839dd1fbca92f7ee34436cc4b8380aee0793a279c56e1daf9c2f38a8593a3f1R180
<details>
<summary>
screenshot of the relevant diff :
</summary>
</details>
see : https://github.com/postcss/postcss/issues/1785

fix whitespace bug

---

test/at-rule.test.ts
test/map.test.ts

invalid sourcemap with at layer

---

README.md

I've been working on `@stylelint/postcss-css-in-js` replacement for styled-components for a long time. It was very out of comfort zone project. I'm glad I finished. It was interesting to learn how PostCSS parses and stringifies.
This PR adds it to the list of known syntaxes. It has no downloads yet, because I just released it. But it has a lot of tests and I tested it on my work projects, which has a lot of different syntax.
Thank you for all your hard work on PostCSS, it is really hard and complex work!
---
Additionally I noticed that two syntaxes need updated repo URL. So I fixed it.

Add postcss-styled-syntax syntax

---

test/parse.test.ts

While working on the different tokenizer I encountered a few cases which have specific behavior in PostCSS but aren't covered by tests.
_Because the tokenizer is less granular it doesn't show in line coverage that these cases are untested._

increase test coverage

---

README.md

First of all, thanks so much for PostCSS and the ecosystem, amazing tool! 🙌
Just wanted to surface the JSDoc types in the config recommendation to allow for autocompletion. (also type-checking if you configure `checkJs: true` in `tsconfig.json`)

Add JSDoc type for config

---

lib/node.d.ts

Hello, this is my first pull request!
Please review and accept if you like the documentation changes.
If this pull request gets accepted, I will improve documentation for the 
whole Post CSS project.
I want to learn Post CSS better, so I have started by writing the documentation
for whole project.

lib/node.d.ts - Improved documentation

---

lib/parser.js
test/location.test.ts

This PR addresses the [issue](https://github.com/postcss/postcss/issues/1876) of `source.end.offset` being off by one.
The problem stemmed from direct use of the token location as the offset when resolving line and column with `getPosition()`, which worked well for `start.offset`, but should point to the index immediately after the node for the `end.offset` to ensure that  `source.slice(start.offset, end.offset)` provides the correct node source.
The solution is straightforward: I've reviewed the parser's instances where the end offset is set and made a simple adjustment off adding 1 (except the final root location that works as expected).
There are still 30 failing tests originating from [postcss-parser-tests](https://github.com/postcss/postcss-parser-tests) that needs to have their …

fix: node end offset location

---

lib/map-generator.js

related change to PostCSS benchmarks : https://github.com/postcss/benchmark/pull/32

improve sourcemap performance

---

lib/postcss.d.ts

If I do something like:
```ts
const result = await postcss([plugin1, plugin2]).process(css)
```
This would correctly log the warning below:
```
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
```
As explained, changing to `process(css, { from: undefined })` prevent the warning. However, when `exactOptionalPropertyTypes` is set to `true` in the `tsconfig.json` it's not possible to do that at all, as `undefined` wouldn't be an allowed type.
TSConfig Reference: [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes)
This PR only adds `undefined` to the type.

Fix `ProcessOptions` interface

---

lib/map-generator.js
lib/no-work-result.js
test/no-work-result.test.ts

see : https://github.com/postcss/postcss/issues/1869

Ensure that `NoWorkResult` and `LazyResult` have the same outcome.

---

lib/processor.js

resolves #1869
- refactor check of all falsy condition of plugins and opts before returing NoWorkResult in Processor.process().
> https://github.com/postcss/postcss/blob/a0a82d3530ce7dfbfe1f12aa76c20f1b3f95eb7c/lib/processor.js#L44-L55
> 
> For a full repro see : https://github.com/romainmenke/postcss-no-work-result-sourcemaps
> 
> By setting `parser: null` as a processing option you can force a `LazyResult`.
> 
> Setting `null` instead of `undefined` is a common mistake, especially when not using TypeScript.
> 
> Is it intentional that `NoWorkResult` and `LazyResult` have different CSS outputs?

refactor: check all falsy conditions of plugins and opts before returning NoWorkResult in process()

---

lib/at-rule.d.ts

The order of lines in the example for AtRule#name got mixed up somehow. This PR corrects the order s.t. the example makes sense and would not produce an error.
https://postcss.org/api/#atrule-name

Fix code example for `name` in at-rule.d.ts

---

lib/map-generator.js
lib/parser.js

1) Hi, i was just looking for how to improve your library, and see strange string when we replace all items on null, i try find when it's need and why we save our array but with null items
Motivation, if we replacy all items, on null, we try to save sourcesContent array length but for what
I only found one place when we use length, when check Content https://github.com/postcss/postcss/blob/219dd756f6867dc0a679567975763b777ac23af3/lib/previous-map.js#L133-L138
But you don't have this case in unit test, and i don't know need thik about this case because all case when we use this func we after nofing do with this data
All rigth, let's imagine what we really check length, next question "we only check wath our array is not empty" or "we use length of array for calcuted/itteration"? 
It's …

Replaced the redundant map function and removed the unused variable

---

lib/at-rule.d.ts
lib/container.d.ts
lib/document.d.ts
lib/root.d.ts
lib/rule.d.ts
test/at-rule.test.ts
test/visitor.test.ts

Parsing something like
```css
@layer a, b, c;
```
with `postcss` will result in an `AtRule` object without a `nodes` property. This however is not reflected by the types.
This PR changes the type of `AtRule#nodes` from `ChildNodes[]` to `ChildNodes[] | undefined` and updates the documentation.
I had to change the types of `Container#nodes` (and undo that change for `Root#nodes`, `Rule#nodes` and `Document#nodes`), I did not find a better approach. Other things I have tried are  #1921 and changing this:
```js
declare class AtRule_ extends Container<ChildNode | undefined>
```
which sadly also does not work because `ChildNode | undefined` does not extend `Node`.
Closes #1920.

Improve AtRule#nodes type

---

lib/node.js
test/warning.test.ts

When `endIndex` is exactly `0` it is ignored and the `end` position will fallback to the end of the node.
Checking that it is a number instead of a simpler boolean check does seem to work as I would expect.

Fix resulting `end` position when `endIndex` is `0` for `rangeBy`

---

lib/css-syntax-error.d.ts

see : https://typescript-eslint.io/rules/only-throw-error/
When using TypeScript it is useful to only throw instances of `Error` (or subclasses thereof)
Currently we get an error for this lint rule with PostCSS on lines like these :
```ts
throw atRule.error('Rule must have valid params')
```
`CssSyntaxError` is a subclass of `Error`, but not declared as such in the `.d.ts` file.

fix `CssSyntaxError` type declaration

---

lib/at-rule.d.ts
lib/comment.d.ts
lib/declaration.d.ts
lib/rule.d.ts

This makes it easier to extend these classes and override these fields
with information that's derived from other, internal fields.
This helps enable https://github.com/sass/dart-sass/issues/88

Declare Node subclass attributes as getters

---

lib/map-generator.js
lib/previous-map.js

I was linting the code with [eslint-plugin-regexp](https://ota-meshi.github.io/eslint-plugin-regexp/) and found some improvements that we could do here.
- Refactor away legacy `RegExp.lastMatch` usage ([they're deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastMatch#browser_compatibility)) 
- Removed an unneeded non-greedy constant quantifier
- Removed an unneeded m flag
Here are the lint results that caught these issues:
```
/Users/bjorn/Work/oss/vite/node_modules/.pnpm/postcss@8.4.39/node_modules/postcss/lib/map-generator.js
78:39  error  Unexpected non-greedy constant quantifier. The quantifier is effectively possessive, so it doesn't matter whether it is greedy or not  regexp/no-useless-lazy …
```

Refactor regex usage

---

lib/declaration.d.ts

Hello, I just happened to notice this typo whilst reviewing the changes in the most recent release. (Thanks Dependabot!)
This was introduced in #1950.
I'm not familiar with PostCSS's internals or release process. As a release of PostCSS has already gone out with this setter name spelled incorrectly, I'm not sure if this warrants additional work to support the prior name and avoid a breaking change. 
Feel free to modify this PR as needed.

Fix typo'd setter name in declaration.d.ts

---

README.md

This Pull Request improves the visual appearance of the images in the README.md file by removing unnecessary line breaks between them, eliminating the unwanted blue link lines that previously appeared and resulting in a cleaner and more cohesive look.
Previously, the images were displayed with line breaks between them, causing blue link lines to appear, which disrupted the clean look of the images. By removing these line breaks, the images now appear without the blue link lines, providing a more cohesive and visually appealing README.
x-ref: [New Default: Underlined Links for Improved Accessibility](https://github.blog/changelog/2023-10-18-new-default-underlined-links-for-improved-accessibility/)

chore(docs): improve visual appearance of images in README.md

---

lib/map-generator.js
lib/parser.js

A small PR.
It is more readable to call `startsWith` than to call `indexOf` and compare the result with zero to determine whether a string starts with a given prefix.
`startsWith` is also more efficient as it only compares at the beginning of the string, while `indexOf` searches the entire string.

Replace `indexOf === 0` with `startsWith`

---

lib/container.d.ts
lib/document.d.ts
lib/list.d.ts
lib/node.d.ts
lib/postcss.d.ts
lib/processor.d.ts
lib/rule.d.ts

This makes it possible for callers to pass in their own
`ReadonlyArray`s, and implicitly documents that these arguments aren't
modified.

Use `ReadonlyArray` for argument types that aren't modified

---

lib/css-syntax-error.js
test/css-syntax-error.test.ts

Add short snippet of code from onelined minified css file

Pretty CssSyntaxError from onelined (minified) css

---

.github/workflows/release.yml
.github/workflows/test.yml

There are leftover actions from commit b952be76f0c7704a99dceb34294117d13e3470a4 that were not updated.
The workflow runs are annotated with the deprecation warnings. (Image from https://github.com/postcss/postcss/actions/runs/10699054789)

Update remaining workflow jobs to use latest version of actions

---

lib/node.js
test/node.test.ts

fixes: https://github.com/postcss/postcss/issues/1979
----
Benchmarks:
```
[16:51:26] Running suite Preprocessors [/Users/romainmenke/projects/postcss-benchmark/preprocessors.js]...
PostCSS sync:      29 ms  (1.0 times faster)
Next PostCSS sync: 29 ms  (1.0 times faster)
PostCSS:           30 ms
Next PostCSS:      31 ms  (1.0 times slower)
...
[16:52:19] Running suite Parsers [/Users/romainmenke/projects/postcss-benchmark/parsers.js]...
PostCSS:      13 ms
Next PostCSS: 13 ms (1.0 times slower)
...
[16:54:02] Running suite Linters [/Users/romainmenke/projects/postcss-benchmark/linters.js]...
Next PostCSS: 207 ms (1.1 times faster)
PostCSS:      219 ms
...
[16:54:14] Running suite Sourcemaps [/Users/romainmenke/projects/postcss-benchmark/sourcemaps.js]...
Next PostCSS: 67 ms (1.0 times …
```

Fix inconsistent position calculations

---

lib/node.js
test/node.test.ts

This is a follow up to : https://github.com/postcss/postcss/pull/1980
When testing PostCSS `v8.4.48` I got some unexpected errors in Stylelint using the `postcss-sugarss` custom syntax.
It seems that [this syntax doesn't expose `source.offset`](https://github.com/postcss/sugarss/issues/105)
To avoid unexpected issues in the community I think it is best to add a fallback where we calculate the correct `offset` if this field is not set by the parser.
This is slower than directly accessing a pre-computed value but that makes PostCSS more resilient.
(Ideally https://github.com/postcss/sugarss/issues/105 is resolved so that they also have the faster code when linting.)

Fix position calculations when `offset` is missing

---

lib/rule.d.ts

This didn't match the actual type or behavior of the field.

Fix the documentation for `RuleRaws.ownSemicolon`

---

lib/parser.js

See: https://github.com/postcss/postcss-parser-tests/pull/28
Rules with semicolons had these assigned to `rule.raws.ownSemicolon` and these are also used when serializing: 
https://github.com/postcss/postcss/blob/7b02c75e5f093b3fdf8d46eeb17c21a52434d827/lib/stringifier.js#L330-L335
However the source positions of the rules weren't adjusted after appending to `rule.raws.ownSemicolon`.
This change makes it so that slicing out the source range for a rule from the input CSS better matches `rule.toString()`

Fix end position of rules with `ownSemicon`

---

lib/parser.js

clarify error message by specify error variable
instead of unknown word it is better for user to see the exacly token cause issue:
closes #2014 
also reference: 
https://github.com/tailwindlabs/tailwindcss/issues/16447#issuecomment-2667452873
https://github.com/saadeghi/daisyui/issues/3453

update: parser.js to clarify error message

---

lib/result.d.ts
lib/result.js

In the `constructor` of class `Result` property `css` is initialized to `undefined` and the same is returned by the method `toString()`.

Change in type definition of property `css` of `result`

---

README.md

- Added a mention for `PostCssense` extension which provide support for intellisense of global classes
- Adds a CSS panel to list down all global classes
- Displays the contents of the global class when hovered over

fix: add a mention for postcssense extension

---

lib/node.d.ts
test/location.test.ts

ref: #2030
The behavior of `node.source.end.offset` is confusing to users. I want to reduce this confusion. So I have tried to describe the behavior in the documentation.

Clarify documentation for `node.source.end.offset`
